//
//  ViewModel.swift
//  trianthropotypesPaschalides
//
//  Created by Angelos Staboulis on 8/6/23.
//

import Foundation
class ViewModel{
    var model = Model()
    func fillQuestions()->[String]{
        model.questionsArray.append("Όταν εκνευρίζεστε, γίνεστε...")
        model.questionsArray.append("Όταν βρεθείτε σε μια\n συζήτηση, συμμετέχετε...")
        model.questionsArray.append("Για να πετύχετε έναν\n στόχο, εργάζεστε...")
        model.questionsArray.append("Όταν έχετε να λύσετε κάποιο\n πρόβλημα,αναζητάτε…")
        model.questionsArray.append("Για ό, τι σας ενοχλεί …")
        model.questionsArray.append("Στις κοινωνικές επαφές και εκδηλώσεις")
        model.questionsArray.append("Όταν σας έρχεται κάτι στο μυαλό")
        model.questionsArray.append("Αν κάποιος διαφωνεί με την άποψή σας")
        model.questionsArray.append("Λέτε τη γνώμη σας")
        model.questionsArray.append("Λέτε τη γνώμη σας")
        model.questionsArray.append("Όταν κάποιος μοιράζεται ένα πρόβλημά\n του μαζί σας,  για να τον βοηθήσετε")
        model.questionsArray.append("Σας χαρακτηρίζει κυρίως")
        model.questionsArray.append("Οι άλλοι σας ακολουθούν, επειδή")
        model.questionsArray.append("Όσον αφορά τους κανόνες")
        model.questionsArray.append("Διαλέγετε στην παρέα σας άτομα κυρίως")
        model.questionsArray.append("Τα δύσκολα")
        model.questionsArray.append("Σε συνθήκες πίεσης στη δουλειά")
        model.questionsArray.append("Σε μια διαφωνία")
        model.questionsArray.append("Όταν σας εκνευρίσουν")
        model.questionsArray.append("Πριν προβείτε σε κάποια ενέργεια")
        model.questionsArray.append("Όταν αναθέτετε σε κάποιον μια εργασία")
        model.questionsArray.append("Όταν έχετε δίκιο")
        model.questionsArray.append("Οι αναμνήσεις σας συνήθως είναι")
        model.questionsArray.append("Οι αναμνήσεις σάς κάνουν να")
        model.questionsArray.append("Οι δικοί σας άνθρωποι λένε για εσάς ότι")
        model.questionsArray.append("Όταν επιστρέφετε στο σπίτι, θέλετε πρώτα")
        model.questionsArray.append("Το πρόγραμμα σας αρέσει")
        model.questionsArray.append("Εργάζεστε με έναν από τους\n παρακάτω τρόπους:")
        model.questionsArray.append("Αν σας παρουσιαστεί κάποιο εμπόδιο")
        model.questionsArray.append("Δίνετε μεγάλη προσοχή στη λεπτομέρεια;")
        model.questionsArray.append("Όταν ερωτευθείτε και σας εγκαταλείψουν")
        model.questionsArray.append("Στη ζωή σας είναι πιο ισχυρo")
        model.questionsArray.append("Όσον αφορά τις υποχρεώσεις σας")
        model.questionsArray.append("Όταν αναλαμβάνετε πολλές δουλειές μαζί")
        model.questionsArray.append("Ξοδεύω εύκολα χρήματα")
        model.questionsArray.append("Όταν προσφέρετε")
        model.questionsArray.append("Όταν βρείτε μπροστά σας\n «λακκούβα» (εμπόδιο)")
        model.questionsArray.append("Όταν βρεθείτε σε αδιέξοδο,αν\n το καράβι βουλιάζει,")
        model.questionsArray.append("Όταν βρέχει")
        model.questionsArray.append("Σε ένα ξέσπασμα")
        return model.questionsArray
    }
    func fillAnswers1()->[String]{
        model.answers1Array.append("επιθετικοί, οξύθυμοι και απρόβλεπτοι.")
        model.answers1Array.append("αλλά κουράζεστε γρήγορα και δεν επιμένετε στις απόψεις σας.")
        model.answers1Array.append("με ταχύτητα και προσήλωση αλλά χωρίς υπομονή και χωρίς πολλή προσοχή στις λεπτομέρειες.")
        model.answers1Array.append("την ευκολότερη λύση. Ή το λύνετε ή το αφήνετε.")
        model.answers1Array.append("δεν σκάτε πολύ. Το προσπερνάτε.")
        model.answers1Array.append("είστε ντροπαλοί στην αρχή, αλλά γρήγορα το ξεπερνάτε και περνάτε καλά.")
        model.answers1Array.append("το σκέφτεστε για λίγο, αλλά ο ενθουσιασμός σας σάς ωθεί να το πείτε ή να το κάνετε αμέσως.")
        model.answers1Array.append("νευριάζετε, στενοχωριέστε, δεν έχετε υπομονή να την εξηγήσετε και διακόπτετε τη συζήτηση.")
        model.answers1Array.append("χωρίς να σας ενδιαφέρει αν οι άλλοι τη δεχθούν.")
        model.answers1Array.append("Βιαστικά και νομίζετε ότι θα γίνει κατανοητή")
        model.answers1Array.append("συζητάτε, παροτρύνοντας και ενθαρρύνοντάς τον λέγοντας του  «μια χαρά είσαι, δεν υπάρχει πρόβλημα».")
        model.answers1Array.append("η ανυπομονησία")
        model.answers1Array.append("τους παρασύρετε με τον ενθουσιασμό σας.")
        model.answers1Array.append("δεν προσέχετε και εύκολα παρακάμπτετε τους κανόνες")
        model.answers1Array.append("ευχάριστα, για να γελάτε.")
        model.answers1Array.append("Σας εκνευρίζουν.")
        model.answers1Array.append("πανικοβάλλεστε, πνίγεστε και εύκολα τα παρατάτε.")
        model.answers1Array.append("εκνευρίζεστε, χάνετε τον έλεγχο και δεν ξέρετε πώς θα αντιδράσετε.")
        model.answers1Array.append("φεύγετε, για να μην παρεκτραπείτε.")
        model.answers1Array.append("υπολογίζετε, μετράτε, όμως από τη βιασύνη σας παρασύρεστε και δεν προσέχετε αν θα δώσετε δικαίωμα για σχόλια.")
        model.answers1Array.append("τον εμπιστεύεστε στην αρχή, αλλά, επειδή δεν έχετε την υπομονή να του εξηγήσετε τι ακριβώς έχετε στο μυαλό σας, καταλήγετε να την διεκπεραιώνετε μόνοι σας.")
        model.answers1Array.append("το υποστηρίζετε, αλλά κουράζεστε γρήγορα και δε σας νοιάζει αν το δεχθούν.")
        model.answers1Array.append("άλλοτε ευχάριστες, άλλοτε δυσάρεστες.")
        model.answers1Array.append("χαμογελάτε.")
        model.answers1Array.append("είστε «στον κόσμο σας» και δεν σας επηρεάζει η γνώμη των άλλων.")
        model.answers1Array.append("να ξεκουραστείτε, για να ηρεμήσετε.")
        model.answers1Array.append("αλλά σας κουράζει και δεν το τηρείτε.")
        model.answers1Array.append("Βιάζεστε να ολοκληρώσετε μια εργασία, γι’ αυτό και προσπερνάτε εύκολα τα εμπόδια.")
        model.answers1Array.append("το αντιμετωπίζετε νευρικά και γρήγορα.")
        model.answers1Array.append("Ναι, αλλά εύκολα την προσπερνάω.")
        model.answers1Array.append("πνιγόσαστε, πονάτε αλλά μόλις βρείτε άλλο το ξεχνάτε.")
        model.answers1Array.append("τα «θέλω» σας από τα «πρέπει» σας.")
        model.answers1Array.append("σας πνίγουν.")
        model.answers1Array.append("πνίγεστε, και τρέχετε να τις διεκπεραιώσετε όσο πιο γρήγορα μπορείτε για να φύγετε από αυτές.")
        model.answers1Array.append("για να περάσω καλά εγώ και όλοι οι δικοί μου.")
        model.answers1Array.append("δίνετε και φεύγετε.")
        model.answers1Array.append("την προσπερνάτε πηγαίνοντας από το πλάι. Την παρακάμπτετε εύκολα.")
        model.answers1Array.append("τολμάτε, πηδάτε πρώτοι και φροντίζετε να σώσετε ό,τι μπορείτε.")
        model.answers1Array.append("δεν νοιάζεστε, γιατί … πέρα βρέχει.")
        model.answers1Array.append("πετάτε ό,τι βρείτε μπροστά σας, χωρίς να υπολογίζετε την αξία του, ούτε και που θα βρεθεί.")
        return model.answers1Array
    }
    func fillAnswers2()->[String]{
        model.answers2Array.append("αμυντικοί, αντιδραστικοί και δεν ξεσπάτε εύκολα.")
        model.answers2Array.append("και αναλύετε τις απόψεις σας με λεπτομέρεια, για να γίνετε κατανοητοί.")
        model.answers2Array.append("προσεκτικά, με μεγάλη υπομονή και πολλή προσοχή στις λεπτομέρειες.")
        model.answers2Array.append("την ευκολότερη λύση. Αν δείτε ότι μετά από πολλή σκέψη δεν μπορείτε να το λύσετε, το αφήνετε για να το επανεξετάσετε αργότερα.")
        model.answers2Array.append("το παρατηρείτε, παραπονιέστε και δεν το προσπερνάτε.")
        model.answers2Array.append("έχετε συνήθως άγχος και είστε γενικά συγκρατημένοι, για να μη δώσετε δικαιώματα για σχόλια. Φεύγετε συνήθως κουρασμένοι.")
        model.answers2Array.append("το επεξεργάζεστε πολύ για να δείτε αν και πώς πρέπει να το πείτε ή να το κάνετε.")
        model.answers2Array.append("αγχώνεστε, στενοχωριέστε και προσπαθείτε να τη στηρίξετε με όσα στοιχεία, αποδείξεις και επιχειρήματα διαθέτετε.")
        model.answers2Array.append("προσεκτικά και αναλυτικά για μην πουν κάτι οι άλλοι")
        model.answers2Array.append("αναλυτικά και με πολύ διάλογο, για να γίνει κατανοητή.")
        model.answers2Array.append("συζητάτε μαζί του, αναλύετε το θέμα διεξοδικά και του δίνετε συμβουλές για να λύσει το πρόβλημά του.")
        model.answers2Array.append("η υπομονή")
        model.answers2Array.append("τους συμβουλεύετε.")
        model.answers2Array.append("ακολουθείτε πιστά τους κανόνες")
        model.answers2Array.append("ενδιαφέροντα, για να συζητάτε.")
        model.answers2Array.append("Σας αγχώνουν.")
        model.answers2Array.append("αγχώνεστε, σκέφτεστε συνέχεια και προσέχετε τα πάντα.")
        model.answers2Array.append("θυμώνετε και σκέφτεστε αν και πώς πρέπει να αντιδράσετε.")
        model.answers2Array.append("ετοιμάζεστε να μιλήσετε, αλλά το ξανασκέφτεστε και κάνετε πίσω.Θυμώνετε με τον εαυτό σας που δεν μιλήσατε")
        model.answers2Array.append("υπολογίζετε και μετράτε με λεπτομέρεια τα πάντα, για να μη δώσετε δικαίωμα να σας σχολιάσουν.")
        model.answers2Array.append("δεν τον εμπιστεύεστε, τον συμβουλεύετε και τον ελέγχετε συνεχώς, επειδή αγχώνεστε για πιθανά λάθη.")
        model.answers2Array.append("το υποστηρίζετε και προσπαθείτε με διάλογο να τους πείσετε να το δεχθούν.")
        model.answers2Array.append("ευχάριστες, αλλά σας θλίβουν.")
        model.answers2Array.append("ονειροπολείτε.")
        model.answers2Array.append("νομίζετε πως τα ξέρετε όλα, είστε αγχώδεις και αντιδραστικοί.")
        model.answers2Array.append("να συζητήσετε για ό,τι σας απασχολεί, για να ηρεμήσετε.")
        model.answers2Array.append("και ορίζει τη ζωή σας. Αγχώνεστε και προσέχετε να μην παρεκκλίνετε από αυτό.")
        model.answers2Array.append("Καθυστερείτε να ολοκληρώσετε μια εργασία, επειδή επεξεργάζεστε μια-μια τις λεπτομέρειες για να αποφύγετε τυχόν εμπόδια.")
        model.answers2Array.append("το αντιμετωπίζετε προσεκτικά και με έλεγχο.")
        model.answers2Array.append("Ναι, και προσπαθώ πολύ να την αναλύσω.")
        model.answers2Array.append("θυμώνετε με τον εαυτό σας και για μια ζωή σκέφτεστε τι θα έπρεπε να είχατε κάνει για να μη σας εγκαταλείψουν.")
        model.answers2Array.append("τα «πρέπει» σας από τα «θέλω» σας.")
        model.answers2Array.append("σας αγχώνουν.")
        model.answers2Array.append("αγχώνεστε και σκέφτεστε πώς θα τις κάνετε, με αποτέλεσμα να χάνεστε και να καθυστερείτε πολύ να τις διεκπεραιώσετε.")
        model.answers2Array.append("για όσα είναι απαραίτητα για μένα και για τους δικούς μου.")
        model.answers2Array.append("δίνετε, κοιτάζετε τον άλλον στα μάτια να δείτε αν είναι ευχαριστημένος και ρωτάτε  «Σου αρέσει;»")
        model.answers2Array.append("γυρίζετε γύρω-γύρω από τη λακκούβα σκεπτόμενοι πώς να την προσπεράσετε.")
        model.answers2Array.append("αγχώνεστε, και από το φόβο σας χάνεστε και δυσκολεύεστε να αποφασίσετε τι να κάνετε.")
        model.answers2Array.append("αγχώνεστε, επειδή βρέχει, και αρχίζετε να μετράτε πόσες σταγόνες πέφτουν.")
        model.answers2Array.append("υπολογίζετε, συγκρατιέστε αλλά πετάτε κάτι που δεν σας χρειάζεται στο πάτωμα")
        return model.answers2Array
    }
    func fillAnswers3()->[String]{
        model.answers3Array.append("επιθετικοί, απόλυτοι και ανυποχώρητα επίμονοι.")
        model.answers3Array.append("αλλά είστε ανυποχώρητοι στις απόψεις σας.")
        model.answers3Array.append("με πάθος, πολύ σκληρά, με επιμονή, με μεγάλο πείσμα και ελέγχετε κάθε λεπτομέρεια.")
        model.answers3Array.append("την καλύτερη λύση. Αν, όμως, συναντήσετε εμπόδιο, κολλάτε και επιμένετε να βρείτε οπωσδήποτε λύση.")
        model.answers3Array.append("σκάτε μέχρι να διορθωθεί.")
        model.answers3Array.append("ελέγχετε στην αρχή το περιβάλλον και, αν το εγκρίνετε, περνάτε καλά.Τις περισσότερες φορές όμως φεύγετε προβληματισμένοι, πράγμα που σας βασανίζει.")
        model.answers3Array.append("το ελέγχετε εξονυχιστικά, και, όταν θεωρήσετε ότι είναι σωστό, το λέτε και το κάνετε οπωσδήποτε.")
        model.answers3Array.append("παλεύετε με μεγάλη υπομονή και επιμονή να την τεκμηριώσετε μέχρι να γίνει αποδεκτή.")
        model.answers3Array.append("και την επιβάλλετε, γιατί θεωρείτε ότι είναι η σωστή.")
        model.answers3Array.append("αναλυτικά και χωρίς διάλογο για να γίνει κατανοητή")
        model.answers3Array.append("συζητάτε μαζί του μεγαλύτερα προβλήματα για να φανούν μικρότερα τα δικά του.")
        model.answers3Array.append("η επιμονή")
        model.answers3Array.append("βάζετε νόμους και κανόνες.")
        model.answers3Array.append("φτιάχνετε δικούς σας κανόνες")
        model.answers3Array.append("με προβλήματα, για να τα βοηθάτε.")
        model.answers3Array.append("Σας προκαλούν.")
        model.answers3Array.append("παθιάζεστε, δίνεστε μέχρι τελικής πτώσεως και δεν τα παρατάτε.")
        model.answers3Array.append("πεισμώνετε, αντιδράτε με επιμονή και δεν υποχωρείτε.")
        model.answers3Array.append("πεισμώνετε και επιμένετε να βρείτε το δίκιο σας.")
        model.answers3Array.append("υπολογίζετε, μετράτε, ελέγχετε και επιμένετε οπωσδήποτε να εκτελεστεί για να μην υπάρξουν σχόλια.")
        model.answers3Array.append("δεν τον εμπιστεύεστε, επειδή πιστεύετε ότι είστε ο μόνος που μπορείτε να το κάνετε.")
        model.answers3Array.append("το υποστηρίζετε και το επιβάλετε χωρίς συζήτηση.")
        model.answers3Array.append("τραυματικές και οδυνηρές.")
        model.answers3Array.append("πονάτε.")
        model.answers3Array.append("είστε πεισματάρηδες, ότι τα ξέρετε και τα κάνετε όλα.")
        model.answers3Array.append("να τα βάλετε όλα σε τάξη, για να ηρεμήσετε.")
        model.answers3Array.append("και πρέπει οπωσδήποτε να τηρηθεί, όχι μόνο από εσάς αλλά και από όλους τους άλλους.")
        model.answers3Array.append("Ξεκινάτε με επιμονή να ολοκληρώσετε μια εργασία, και, αν συναντήσετε εμπόδια, σας εξιτάρουν και ορμάτε με πάθος για να τα καταρρίψετε.")
        model.answers3Array.append("το αντιμετωπίζετε με επιμονή και πείσμα.")
        model.answers3Array.append("Ναι, και αγωνίζομαι για την τελειότητα.")
        model.answers3Array.append("παθιάζεστε, «κολλάτε» και βασανίζεστε σε όλη σας τη ζωή για το άτομο που σας πλήγωσε. Ψάχνετε να βρείτε την ευκαιρία για να εκδικηθείτε. Δεν το ξεχνάτε, ακόμη και να βρείτε άλλο.")
        model.answers3Array.append("το πάθος σας από τα «πρέπει» και τα «θέλω» σας.")
        model.answers3Array.append("παλεύετε γι’ αυτές.")
        model.answers3Array.append("παθιάζεστε, παλεύετε και πρέπει οπωσδήποτε να τις διεκπεραιώσετε.")
        model.answers3Array.append("για να περάσω καλά εγώ και όσοι από τους δικούς μου θεωρώ ότι αξίζουν.")
        model.answers3Array.append("δίνετε και δεν ρωτάτε τίποτα, γιατί, αν σας πουν ότι δεν τους αρέσει, θα τους το φέρετε στο κεφάλι.")
        model.answers3Array.append("πηδάτε να αποφύγετε την λακκούβα και πέφτετε στην επόμενη, όπου και … κολλάτε! Κάθεστε πάνω στα προβλήματα.")
        model.answers3Array.append("σηκώνετε τα μανίκια, μπαίνετε κάτω από το καράβι και λέτε: «Πού θα πάει, εγώ θα το σώσω!»")
        model.answers3Array.append("πάτε και κάθεστε κάτω από τη βροχή, για να βγείτε βρεγμένοι.")
        model.answers3Array.append("κάνετε υπομονή, αλλά στο τέλος αναποδογυρίζετε όλο το τραπέζι.")
        return model.answers3Array
    }
}
